version: '3.7'

services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8090:8080
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - db

  httpd:
    container_name: httpd
    build:
      context: ./html
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:

volumes:
  db-data: