- name: Launch Database Container
  docker_container:
    name: db
    image: pbonnefoy/simpleapi-db:latest
    pull: true
    recreate: true
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd