- hosts: all
  gather_facts: false
  become: true

  roles: # Les 5 étapes à effectuer, dans l'ordre :
    - install-docker
    - create-network
    - launch-database
    - launch-app
    - launch-proxy