name: CI devops 2023 # Nom du fichier
on:
  # On lance le job pour les branches main et develop
  push:
    branches: [master, develop]
  pull_request:


jobs:
  test-backend: # Job backend
    runs-on: ubuntu-22.04
    steps:
      # vérification du code github en utilisant actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Utilisation d'un JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # On build l'image, et on la teste avec SonarCloud, pour être sûr d'avoir un code propre et sécurisé.
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=simpleapi-tpdevops_simpleapi -Dsonar.organization=simpleapi-tpdevops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

  # Job pour build et push l'image docker
  build-and-push-docker-image:
    needs: test-backend
    # On effectue les actions suivantes seulement si le backend fonctionne
    runs-on: ubuntu-22.04

    # Et on sépare en étapes notre processus de connection, puis de push.
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/simpleapi-backend
          push: ${{ github.ref == 'refs/heads/develop' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Database
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/simpleapi-db
          push: ${{ github.ref == 'refs/heads/develop' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./html
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/simpleapi-httpd
          push: ${{ github.ref == 'refs/heads/develop' }}